workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_credentials # Only for CM_CERTIFICATE_PASSWORD
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          
      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          
          # 1. Import Certificate (P12) from repo
          # standard password 'password' should be in CM_CERTIFICATE_PASSWORD var
          keychain add-certificates \
            --certificate signing/distribution.p12 \
            --certificate-password "$CM_CERTIFICATE_PASSWORD"
            
          # 2. Install Provisioning Profile from repo
          PROFILE_UUID="bc145a22-aaba-4800-9608-e8fd063229c9"
          PROFILE_SRC="signing/JM_Audiobooks_App_Store.mobileprovision"
          PROFILE_DST="$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"
          
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PROFILE_SRC" "$PROFILE_DST"
          echo "Installed profile to $PROFILE_DST"

      - name: Build IPA
        script: |
          # Force settings to match our manual signing artifacts
          PROFILE_UUID="bc145a22-aaba-4800-9608-e8fd063229c9"
          BUNDLE_ID="com.jmaudiobooks.jmaudiobooks"
          TEAM_ID="QY25P2CW87"
          IDENTITY="Apple Distribution" # Matches the certificate CN
          
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-flags "PROVISIONING_PROFILE_SPECIFIER=$PROFILE_UUID PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID DEVELOPMENT_TEAM=$TEAM_ID CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='$IDENTITY'"

    artifacts:
      - "build/ios/ipa/*.ipa"
      - "*.dSYM.zip"
