workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest # Uses the latest stable Xcode version
      node: latest  # Uses the latest stable Node.js version
      groups:
        - app_store_credentials # You need to create this group in CodeMagic UI variables
    scripts:
      - name: Install npm dependencies
        script: npm install

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Initialize Keychain
        script: keychain initialize

      - name: Set up code signing
        script: |
          keychain initialize
          
          # Decode signing files using Python for safety
          python3 -c "
          import base64, os
          
          def decode_env(var_name, output_path):
              try:
                  data = os.environ.get(var_name, '')
                  # Strip whitespace and newlines just in case
                  clean_data = data.replace(' ', '').replace('\n', '').replace('\r', '')
                  decoded = base64.b64decode(clean_data)
                  with open(output_path, 'wb') as f:
                      f.write(decoded)
                  print(f'Successfully decoded {var_name} to {output_path}')
              except Exception as e:
                  print(f'Error decoding {var_name}: {str(e)}')
                  exit(1)
          
          # Ensure directory exists
          profile_dir = os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles')
          if not os.path.exists(profile_dir):
              os.makedirs(profile_dir)
              
          decode_env('CM_CERTIFICATE', '/tmp/certificate.p12')
          decode_env('CM_PROVISIONING_PROFILE', os.path.join(profile_dir, 'profile.mobileprovision'))
          "
          
          keychain add-certificates \
            --certificate /tmp/certificate.p12 \
            --certificate-password "$CM_CERTIFICATE_PASSWORD"

      - name: Set up code signing settings
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          # Build the iOS app
          # Note: Using .xcodeproj because no Podfile/Workspace was found
          xcode-project build-ipa \
            --project "ios/App/App.xcodeproj" \
            --scheme "App"

    artifacts:
      - "build/ios/ipa/*.ipa"
      - "/tmp/xcodebuild_logs/*.log"
      - "*.dSYM.zip"

    publishing:
      app_store_connect:
        # Use the API Key variables for publishing
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
