workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.jmaudiobooks.jmaudiobooks"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          
      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          
          # Import Certificate
          keychain add-certificates \
            --certificate signing/distribution.p12 \
            --certificate-password "$CM_CERTIFICATE_PASSWORD"
          
          # Verify keychain
          security find-identity -v -p codesigning
            
          # Install Provisioning Profile
          PROFILE_UUID="bc145a22-aaba-4800-9608-e8fd063229c9"
          PROFILE_SRC="signing/JM_Audiobooks_App_Store.mobileprovision"
          PROFILE_FOLDER="$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_DST="$PROFILE_FOLDER/$PROFILE_UUID.mobileprovision"
          
          mkdir -p "$PROFILE_FOLDER"
          cp "$PROFILE_SRC" "$PROFILE_DST"
          
          # Debug: Verify profile installation
          echo "Installed profile to: $PROFILE_DST"
          ls -l "$PROFILE_FOLDER"
          
          # Debug: Read profile name using security tool
          security cms -D -i "$PROFILE_DST" | grep -A 1 "Name"
          security cms -D -i "$PROFILE_DST" | grep -A 1 "UUID"

      - name: Build and Archive
        script: |
          set -e
          set -o pipefail

          # Create ExportOptions.plist
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>QY25P2CW87</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.jmaudiobooks.jmaudiobooks</key>
              <string>JM Audiobooks App Store</string>
            </dict>
            <key>signingCertificate</key>
            <string>Apple Distribution</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF

          # BUILD THE ARCHIVE
          mkdir -p build/ios/xcarchive
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/ios/xcarchive/App.xcarchive \
            archive

          # EXPORT THE IPA
          mkdir -p build/ios/ipa
          xcodebuild \
            -exportArchive \
            -archivePath build/ios/xcarchive/App.xcarchive \
            -exportOptionsPlist export_options.plist \
            -exportPath build/ios/ipa

          # Verify artifact exists
          ls -R build/ios/ipa

    artifacts:
      - "build/ios/ipa/*.ipa"
      - "build/ios/xcarchive/*.xcarchive"

    publishing:
      app_store_connect:
        # Manual authentication using environment variables
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        apple_id: 6756834122 # Numeric ID from your App Store Connect screenshot
        submit_to_testflight: true
        beta_groups:
          - "External Testers"
