default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Authenticate using the API Key (Native Base64 Support)
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_PRIVATE_KEY"], # Should be Base64 encoded
      is_key_content_base64: true,                # Tells Fastlane to decode it
      in_house: false                             # Standard Play Store
    )

    # Upload to TestFlight
    upload_to_testflight(
      api_key: api_key,
      ipa: "./ios/App/output/App.ipa",
      skip_waiting_for_build_processing: true # Don't wait for Apple processing
    )
  end
end
